version: '3.8'
services:
  supermicro-java-ikvm:
    image: ghcr.io/mistercalvin/supermicro-java-ikvm:latest
    container_name: supermicro-java-ikvm
    environment:
      TZ: UTC
      USER_ID: 2000
      GROUP_ID: 1000
      KVM_HOST: 192.168.1.152 # IP or Hostname
      KVM_USER: ADMIN # Your IPMI Username
      KVM_PASS: 335ruugm35 # Your IPMI Password
      DISPLAY_WIDTH: 1024 # Display Width
      DISPLAY_HEIGHT: 768 # Display Height
    ports:
      - 5800:5800 # Web UI Port
      - 5900:5900 # VNC Port
    volumes:
      - ./vmedia:/app/vmedia/ # Virtual Media ISO's
      - ./screenshots:/app/screenshots/ # Screenshots / Recordings
      - supermicro-java-ikvm:/config/ # Persistent Configuration for user preferences
    restart: no

volumes:
  supermicro-java-ikvm:
    name: supermicro-java-ikvm
